% Determine specs of a mix containing oxygenates.
%  Jake Miller, April 13, 2021, last edited June 18, 2021
function alcmixspecs = alcmix(VFAmatrix,VPsubset)
new_molfracs = VFAmatrix(:,3) ./ sum(VFAmatrix(:,3));
alcmixspecs =[RaoultsLawCalc(new_molfracs,VPsubset), TorabianSobatiFP(new_molfracs,VFAmatrix(:,14)),...
    LinearBlend(VFAmatrix(:,6),VFAmatrix(:,end)), GNviscosity(new_molfracs,VFAmatrix(:,7)),...
    LinearBlend(VFAmatrix(:,8),VFAmatrix(:,end)), LinearBlend(VFAmatrix(:,9),VFAmatrix(:,end)),...
    LinearBlend(VFAmatrix(:,10),VFAmatrix(:,3)), LinearBlend(VFAmatrix(:,11),VFAmatrix(:,3)),...
    GNviscosity(new_molfracs,VFAmatrix(:,15)),GNviscosity(new_molfracs,VFAmatrix(:,16))];
% Note: RON and CN (second to last and last properties) use mole fraction
% instead of mass fraction.
end
